name: 'Pull Request Terraform Infra'
on:
  pull_request:
  workflow_dispatch:

env:
      env_var: "dev"
      working-directory: terraform
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      
jobs:
  Azure_Infra_Cost: 
    name: 'Cost of Azure Infra'
    runs-on: ubuntu-latest   
    
    permissions:
      id-token: write
      contents: write
      pull-requests: write

    defaults:
      run:
        shell: bash
   
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Infracost
      uses: infracost/actions/setup@v1
      with:
        api-key: ${{ secrets.INFRACOST_API_KEY }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false 

    - name: Terraform Init
      working-directory: ${{ env.working-directory }}
      run: terraform init

    - name: Terraform Plan
      working-directory: ${{ env.working-directory }}
      run: terraform plan -out tfplan.binary -var-file=environment/${{env.env_var}}/${{env.env_var}}.tfvars

    - name: Terraform Show
      working-directory: ${{ env.working-directory }}
      run: terraform show -json tfplan.binary > plan.json

    - name: Generate Infracost JSON
      run: infracost breakdown --path plan.json --format json --out-file /tmp/infracost.json
      working-directory: ${{ env.working-directory }}
    
    - name: Infracost Actions
      uses: infracost/actions/comment@v1
      with:
        path: /tmp/infracost.json
        behavior: update

  deploy_infra_azure:
    name: 'Deploy Azure Infra'
    runs-on: ubuntu-latest 
    needs: Azure_Infra_Cost
    environment: prod
    steps:
    - name: Terraform Apply
      working-directory: ${{ env.working-directory }}
      run: terraform apply -var-file=environment/${{env.env_var}}/${{env.env_var}}.tfvars

    
